### ISSUE TITLE
model url 404

### ISSUE THREAD

**Issue by A-new-b** [jacklishufan/InstructAny2Pix#6]
the [model link](https://huggingface.co/jacklishufan/instructany2pix/tree/main) is 404, did you close your repo?

**Comment by jacklishufan** [comment]
Please refer to the readme update:
May 23: We temporally unlisted the model checkpoint due to [safety concerns](https://laion.ai/notes/laion-maintenance/) regarding LAION. We plan to retrain the model with clean data in near future.

To comply with University policy, we will release model after the LAION safety review is finished and the official dataset is re-published. However, if this does not happen by the end of summer, we plans to retrain the model using public-available alternative datasets (e.g. COYO-700M)
